version: '3'
services:
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secretPassword
    ports:
      - 27017:27017
networks:
  backend:
  frontend:

